### ISSUE TITLE
Error when loading a workflow in a JTA context: "detached entity passed to persist: finance.tradista.flow.model.Condition"

### ISSUE THREAD

**Issue by oasuncion** [oasuncion/tradista-flow#19]
When a workflow containing a ConditionalAction is being loaded in a JTA based transaction, the technical error below is encountered.

**Current behaviour:** technical error, transaction rollbacked
**Expected behaviour:** workflow being loaded without any error 

Application Server : WildFly 27.0.1
Java version: OpenJDK (RedHat distribution)17.0.5.0.8-2

```
_2023-08-20 17:57:24,640 WARN  [com.arjuna.ats.arjuna] (default task-1) ARJUNA012125: TwoPhaseCoordinator.beforeCompletion - failed for SynchronizationImple< 0:ffffac179001:-2e4ec625:64e2362c:10c, org.wildfly.transaction.client.AbstractTransaction$AssociatingSynchronization@54a27579 >: jakarta.persistence.PersistenceException: Converting `org.hibernate.PersistentObjectException` to JPA `PersistenceException` : detached entity passed to persist: finance.tradista.flow.model.Condition
	at org.hibernate@6.1.5.Final//org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:165)
	at org.hibernate@6.1.5.Final//org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:175)
	at org.hibernate@6.1.5.Final//org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:182)
	at org.hibernate@6.1.5.Final//org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1426)
	at org.hibernate@6.1.5.Final//org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:476)
	at org.hibernate@6.1.5.Final//org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2233)
	at org.hibernate@6.1.5.Final//org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:1929)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:439)
	at org.hibernate@6.1.5.Final//org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl.beforeCompletion(JtaTransactionCoordinatorImpl.java:356)
	at org.hibernate@6.1.5.Final//org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:47)
	at org.hibernate@6.1.5.Final//org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:37)
	at org.jboss.as.transactions@27.0.1.Final//org.jboss.as.txn.service.internal.tsr.JCAOrderedLastSynchronizationList.beforeCompletion(JCAOrderedLastSynchronizationList.java:113)
	at org.wildfly.transaction.client@3.0.0.Final//org.wildfly.transaction.client.AbstractTransaction.performConsumer(AbstractTransaction.java:236)
	at org.wildfly.transaction.client@3.0.0.Final//org.wildfly.transaction.client.AbstractTransaction.performConsumer(AbstractTransaction.java:247)
	at org.wildfly.transaction.client@3.0.0.Final//org.wildfly.transaction.client.AbstractTransaction$AssociatingSynchronization.beforeCompletion(AbstractTransaction.java:292)
	at org.jboss.jts//com.arjuna.ats.internal.jta.resources.arjunacore.SynchronizationImple.beforeCompletion(SynchronizationImple.java:76)
	at org.jboss.jts//com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.beforeCompletion(TwoPhaseCoordinator.java:360)
	at org.jboss.jts//com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:91)
	at org.jboss.jts//com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162)
	at org.jboss.jts//com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1295)
	at org.jboss.jts//com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:128)
	at org.jboss.jts.integration@5.13.0.Final//com.arjuna.ats.jbossatx.BaseTransactionManagerDelegate.commit(BaseTransactionManagerDelegate.java:94)
	at org.wildfly.transaction.client@3.0.0.Final//org.wildfly.transaction.client.LocalTransaction.commitAndDissociate(LocalTransaction.java:78)
	at org.wildfly.transaction.client@3.0.0.Final//org.wildfly.transaction.client.ContextTransactionManager.commit(ContextTransactionManager.java:71)
	at org.jboss.as.ejb3@27.0.1.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.endTransaction(CMTTxInterceptor.java:91)
	at org.jboss.as.ejb3@27.0.1.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:284)
	at org.jboss.as.ejb3@27.0.1.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:390)
	at org.jboss.as.ejb3@27.0.1.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:160)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
	at org.jboss.as.weld.common@27.0.1.Final//org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:89)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3@27.0.1.Final//org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3@27.0.1.Final//org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:47)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3@27.0.1.Final//org.jboss.as.ejb3.security.IdentityOutflowInterceptor.processInvocation(IdentityOutflowInterceptor.java:73)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3@27.0.1.Final//org.jboss.as.ejb3.security.SecurityDomainInterceptor.processInvocation(SecurityDomainInterceptor.java:44)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3@27.0.1.Final//org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(StartupAwaitInterceptor.java:22)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3@27.0.1.Final//org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3@27.0.1.Final//org.jboss.as.ejb3.deployment.processors.EjbSuspendInterceptor.processInvocation(EjbSuspendInterceptor.java:45)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3@27.0.1.Final//org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:67)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ee@27.0.1.Final//org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:60)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:438)
	at org.wildfly.security.elytron-base@2.0.0.Final//org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:633)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.AccessCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:57)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation@1.7.0.Final//org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
	at org.jboss.as.ee@27.0.1.Final//org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:198)
	at org.jboss.as.ejb3@27.0.1.Final//org.jboss.as.ejb3.remote.LocalEjbReceiver.processInvocation(LocalEjbReceiver.java:257)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:499)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.protocol.remote.RemotingEJBClientInterceptor.handleInvocation(RemotingEJBClientInterceptor.java:52)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:514)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.TransactionPostDiscoveryInterceptor.handleInvocation(TransactionPostDiscoveryInterceptor.java:82)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:514)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.DiscoveryEJBClientInterceptor.handleInvocation(DiscoveryEJBClientInterceptor.java:116)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:514)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.NamingEJBClientInterceptor.handleInvocation(NamingEJBClientInterceptor.java:69)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:514)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.AuthenticationContextEJBClientInterceptor.lambda$handleInvocation$0(AuthenticationContextEJBClientInterceptor.java:45)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.AuthenticationContextEJBClientInterceptor.call(AuthenticationContextEJBClientInterceptor.java:59)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.AuthenticationContextEJBClientInterceptor.handleInvocation(AuthenticationContextEJBClientInterceptor.java:44)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:514)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.TransactionInterceptor.handleInvocation(TransactionInterceptor.java:205)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:514)
	at org.wildfly.common@1.6.0.Final//org.wildfly.common.context.Contextual.runExConsumer(Contextual.java:203)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.EJBClientInvocationContext.sendRequestInitial(EJBClientInvocationContext.java:341)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.EJBInvocationHandler.invoke(EJBInvocationHandler.java:178)
	at org.jboss.ejb-client@5.0.1.Final//org.jboss.ejb.client.EJBInvocationHandler.invoke(EJBInvocationHandler.java:116)
	at deployment.app-2.0.0.ear.web-2.0.0.war/jdk.proxy32/jdk.proxy32.$Proxy168.getWorkflowByName(Unknown Source)
	at deployment.app-2.0.0.ear.web-2.0.0.war//finance.tradista.core.workflow.service.WorkflowBusinessDelegate.lambda$0(WorkflowBusinessDelegate.java:46)
	at org.wildfly.common@1.6.0.Final//org.wildfly.common.context.Contextual.runExFunction(Contextual.java:287)
	at org.wildfly.security.elytron-base@2.0.0.Final//org.wildfly.security.auth.client.AuthenticationContext.runAsSupplierEx(AuthenticationContext.java:361)
	at deployment.app-2.0.0.ear.web-2.0.0.war//finance.tradista.core.common.util.SecurityUtil.runEx(SecurityUtil.java:62)
	at deployment.app-2.0.0.ear.web-2.0.0.war//finance.tradista.core.workflow.service.WorkflowBusinessDelegate.getWorkflowByName(WorkflowBusinessDelegate.java:46)
	at deployment.app-2.0.0.ear.web-2.0.0.war//finance.tradista.security.gcrepo.ui.GCRepoTradeView.init(GCRepoTradeView.java:134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:83)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:66)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:122)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:164)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.util.bean.IsolatedForwardingBean.create(IsolatedForwardingBean.java:45)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.ViewScopeContextManager.createBean(ViewScopeContextManager.java:132)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.ViewScopeContext.get(ViewScopeContext.java:111)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.contexts.PassivatingContextWrapper$AbstractPassivatingContextWrapper.get(PassivatingContextWrapper.java:84)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:680)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.module.web.el.AbstractWeldELResolver.lookup(AbstractWeldELResolver.java:107)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.module.web.el.AbstractWeldELResolver.getValue(AbstractWeldELResolver.java:90)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:139)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:164)
	at org.glassfish.expressly@5.0.0//org.glassfish.expressly.parser.AstIdentifier.getValue(AstIdentifier.java:97)
	at org.glassfish.expressly@5.0.0//org.glassfish.expressly.parser.AstValue.getBase(AstValue.java:314)
	at org.glassfish.expressly@5.0.0//org.glassfish.expressly.parser.AstValue.getValue(AstValue.java:140)
	at org.glassfish.expressly@5.0.0//org.glassfish.expressly.ValueExpressionImpl.getValue(ValueExpressionImpl.java:138)
	at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:73)
	at jakarta.faces.api//jakarta.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:207)
	at jakarta.faces.api//jakarta.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:176)
	at jakarta.faces.api//jakarta.faces.component.UIOutput.getConverter(UIOutput.java:107)
	at jakarta.faces.api//jakarta.faces.component.UIOutput.markInitialState(UIOutput.java:164)
	at jakarta.faces.api//jakarta.faces.component.UIInput.markInitialState(UIInput.java:511)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.FaceletViewHandlingStrategy.markInitialState(FaceletViewHandlingStrategy.java:1209)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.FaceletViewHandlingStrategy.markInitialState(FaceletViewHandlingStrategy.java:1213)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.FaceletViewHandlingStrategy.markInitialState(FaceletViewHandlingStrategy.java:1213)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.FaceletViewHandlingStrategy.markInitialState(FaceletViewHandlingStrategy.java:1213)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.FaceletViewHandlingStrategy.markInitialState(FaceletViewHandlingStrategy.java:1213)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.FaceletViewHandlingStrategy.markInitialState(FaceletViewHandlingStrategy.java:1213)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.FaceletViewHandlingStrategy.markInitialState(FaceletViewHandlingStrategy.java:1213)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.FaceletViewHandlingStrategy.markInitialState(FaceletViewHandlingStrategy.java:1213)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.FaceletViewHandlingStrategy.markInitialState(FaceletViewHandlingStrategy.java:1213)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.FaceletViewHandlingStrategy.markInitialState(FaceletViewHandlingStrategy.java:1213)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.FaceletViewHandlingStrategy.markInitialState(FaceletViewHandlingStrategy.java:1213)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.FaceletViewHandlingStrategy.markInitialState(FaceletViewHandlingStrategy.java:1200)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.application.view.FaceletViewHandlingStrategy.buildView(FaceletViewHandlingStrategy.java:360)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:70)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
	at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:178)
	at jakarta.faces.api//jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:692)
	at jakarta.faces.api//jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.smallrye.opentracing-contrib//io.smallrye.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:69)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.security.elytron-web.undertow-server@3.0.0.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.lambda$handleRequest$1(ElytronRunAsHandler.java:68)
	at org.wildfly.security.elytron-base@2.0.0.Final//org.wildfly.security.auth.server.FlexibleIdentityAssociation.runAsFunctionEx(FlexibleIdentityAssociation.java:103)
	at org.wildfly.security.elytron-base@2.0.0.Final//org.wildfly.security.auth.server.Scoped.runAsFunctionEx(Scoped.java:161)
	at org.wildfly.security.elytron-base@2.0.0.Final//org.wildfly.security.auth.server.Scoped.runAs(Scoped.java:73)
	at org.wildfly.security.elytron-web.undertow-server@3.0.0.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.handleRequest(ElytronRunAsHandler.java:67)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.3.0.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.core@2.3.0.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at org.wildfly.security.elytron-web.undertow-server-servlet@3.0.0.Final//org.wildfly.elytron.web.undertow.server.servlet.CleanUpHandler.handleRequest(CleanUpHandler.java:38)
	at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@27.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@27.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@27.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
	at org.wildfly.extension.undertow@27.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
	at org.wildfly.extension.undertow@27.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
	at org.wildfly.extension.undertow@27.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
	at org.wildfly.extension.undertow@27.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
	at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
	at io.undertow.core@2.3.0.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:391)
	at io.undertow.core@2.3.0.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at org.jboss.xnio@3.8.8.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.hibernate.PersistentObjectException: detached entity passed to persist: finance.tradista.flow.model.Condition
	at org.hibernate@6.1.5.Final//org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:121)
	at org.hibernate@6.1.5.Final//org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:118)
	at org.hibernate@6.1.5.Final//org.hibernate.internal.SessionImpl.persistOnFlush(SessionImpl.java:799)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.spi.CascadingActions$8.cascade(CascadingActions.java:342)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.spi.CascadingActions$8.cascade(CascadingActions.java:332)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:511)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:432)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:218)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.internal.Cascade.cascade(Cascade.java:151)
	at org.hibernate@6.1.5.Final//org.hibernate.event.internal.AbstractSaveEventListener.cascadeBeforeSave(AbstractSaveEventListener.java:442)
	at org.hibernate@6.1.5.Final//org.hibernate.event.internal.DefaultPersistEventListener.justCascade(DefaultPersistEventListener.java:167)
	at org.hibernate@6.1.5.Final//org.hibernate.event.internal.DefaultPersistEventListener.entityIsPersistent(DefaultPersistEventListener.java:160)
	at org.hibernate@6.1.5.Final//org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:125)
	at org.hibernate@6.1.5.Final//org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:118)
	at org.hibernate@6.1.5.Final//org.hibernate.internal.SessionImpl.persistOnFlush(SessionImpl.java:799)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.spi.CascadingActions$8.cascade(CascadingActions.java:342)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.spi.CascadingActions$8.cascade(CascadingActions.java:332)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:511)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:432)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:218)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.internal.Cascade.cascadeCollectionElements(Cascade.java:545)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.internal.Cascade.cascadeCollection(Cascade.java:475)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:435)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:218)
	at org.hibernate@6.1.5.Final//org.hibernate.engine.internal.Cascade.cascade(Cascade.java:151)
	at org.hibernate@6.1.5.Final//org.hibernate.event.internal.AbstractFlushingEventListener.cascadeOnFlush(AbstractFlushingEventListener.java:155)
	at org.hibernate@6.1.5.Final//org.hibernate.event.internal.AbstractFlushingEventListener.prepareEntityFlushes(AbstractFlushingEventListener.java:145)
	at org.hibernate@6.1.5.Final//org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:79)
	at org.hibernate@6.1.5.Final//org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:38)
	at org.hibernate@6.1.5.Final//org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
	at org.hibernate@6.1.5.Final//org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1422)
	... 178 more_
```

**Comment by oasuncion** [comment]
It has been fixed and will be part of v2.1.0.
